type User @table {
  displayName: String!
  createdAt: Timestamp!
  email: String
  photoUrl: String
}

type NoTask @table {
  title: String!
  reasonNotDoing: NoTaskReason!
  createdAt: Timestamp!
  status: String!
  description: String
  category: NoTaskCategory
  deferredUntil: Date
  user: User
}

type NoTaskCategory @table {
  name: String!
  createdAt: Timestamp!
  description: String
  user: User
}

type NoTaskReason @table {
  reasonText: String!
  createdAt: Timestamp!
  description: String
  user: User
}